# Generated by Django 4.1 on 2023-05-01 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_auto_20230403_1411"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
    ]
